# Generated by Django 3.0.7 on 2020-06-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20200628_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='latest_modified_date',
            field=models.DateField(),
        ),
    ]
