# Generated by Django 3.0.7 on 2020-06-28 14:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apis', '0003_auto_20200628_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='download_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='download_apis', to=settings.AUTH_USER_MODEL),
        ),
    ]
